language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fontforge
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/
  - bundle
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
script: bundle exec rake
